dependencies {
    implementation project(":core:common-core")
    implementation project(":core:redis-core")
    // Spring Cloud Gateway
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    // Eureka Client for Service Discovery (Eureka 클라이언트)
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    // Config Client
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    // SpringDoc OpenAPI WebFlux UI (Swagger)
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.8.9'
    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
}
