dependencies {
    implementation project(":core:common-core")

    // Spring Batch
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    // JDBC
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    // JSON
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    // MySQL JDBC
    runtimeOnly 'com.mysql:mysql-connector-j'
    // Eureka Client for Service Discovery
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
}
